[package]
name = "shielder"
version = "0.1.0"
authors = ["Cardinal Cryptography"]
edition = "2021"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"
license = "Apache 2.0"
publish = false

[lib]
name = "shielder"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-serialize = { version = "^0.3.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

ink = { git = "https://github.com/paritytech/ink", rev = "4655a8b4413cb50cbc38d1b7c173ad426ab06cde", default-features = false }
openbrush = { git = "https://github.com/727-Ventures/openbrush-contracts/", tag = "3.0.0-beta", default-features = false, features = ["psp22", "ownable"] }

relations = { git = "https://github.com/Cardinal-Cryptography/aleph-node", branch = "snarkeling", package = "relations", default-features = false }
snarcos-extension = { git = "https://github.com/Cardinal-Cryptography/aleph-node", branch = "snarkeling", package = "snarcos-extension", default-features = false, features = ["ink-as-dependency"] }

[features]
default = ["std"]
std = [
    "ark-serialize/std",
    "scale/std",
    "scale-info/std",

    "ink/std",
    "openbrush/std",

    "relations/std",
    "snarcos-extension/std",
]
ink-as-dependency = []
