[package]
name = "shielder-contract"
version = "0.1.0"
authors = ["Cardinal"]
homepage = "https://alephzero.org"
repository = "https://github.com/Cardinal-Cryptography/zk-apps"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.79", default-features = false }
ink = { version = "5.0.0-rc", default-features = false }
serde = { version = "1.0.197", default-features = false, features = ["derive"] }

[dev-dependencies]
drink = "0.9.0"
rand = { version = "0.8.5", default-features = false }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
e2e-tests = []
