[package]
name = "shielder"
version = "0.1.0"
authors = ["Cardinal Cryptography"]
edition = "2021"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"
license = "Apache 2.0"
publish = false

[lib]
name = "shielder"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-serialize = { version = "^0.3.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

ink = { version = "~4.0.1",  default-features = false }
openbrush = { git = "https://github.com/727-Ventures/openbrush-contracts/", tag = "3.0.0", default-features = false, features = ["psp22", "ownable"] }

liminal-ark-relations = { version = "0.4.0", default-features = false }
baby-liminal-extension = { git = "https://github.com/Cardinal-Cryptography/aleph-node", default-features = false, features = ["ink", "ink-as-dependency"] }

[features]
default = ["std"]
std = [
    "ark-serialize/std",
    "scale/std",
    "scale-info/std",

    "ink/std",
    "openbrush/std",

    "liminal-ark-relations/std",
    "baby-liminal-extension/ink-std",
]
ink-as-dependency = []
