name: Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rust-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run format check for `shielder/cli`
        run: cd shielder/cli/ && cargo fmt --all --check

      - name: Run clippy for `shielder/cli`
        run: cd shielder/cli/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/cli`
        run: cd shielder/cli/ && cargo test


      - name: Run format check for `shielder/contract`
        run: cd shielder/contract/ && cargo fmt --all --check

      - name: Run clippy for `shielder/contract`
        run: cd shielder/contract/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/contract`
        run: cd shielder/contract/ && cargo test


      - name: Run format check for `shielder/public_token`
        run: cd shielder/public_token/ && cargo fmt --all --check

      - name: Run clippy for `shielder/public_token`
        run: cd shielder/public_token/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/public_token`
        run: cd shielder/public_token/ && cargo test

  build-contracts:
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: "public.ecr.aws/p6e8q1z1/ink-dev:1.0.0"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown


      - name: Build public token contract
        run: |
          docker run                         \
            -v ${{ github.workspace }}:/code \
            --platform linux/amd64           \
            ${{ env.DOCKER_IMAGE }}         \
            cargo contract build --manifest-path shielder/public_token/Cargo.toml

      - name: Build shielder contract
        run: |
          docker run                         \
            -v ${{ github.workspace }}:/code \
            --platform linux/amd64           \
            ${{ env.DOCKER_IMAGE }}         \
            cargo contract build --manifest-path shielder/contract/Cargo.toml
