name: Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  legacy-shielder-rust-checks:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2022-11-28

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run format check for `shielder/cli`
        run: cd legacy-shielder/cli/ && cargo fmt --all --check

      - name: Run clippy for `shielder/cli`
        run: cd legacy-shielder/cli/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/cli`
        run: cd legacy-shielder/cli/ && cargo test


      - name: Run format check for `shielder/contract`
        run: cd legacy-shielder/contract/ && cargo fmt --all --check

      - name: Run clippy for `shielder/contract`
        run: cd legacy-shielder/contract/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/contract`
        run: cd legacy-shielder/contract/ && cargo test


      - name: Run format check for `shielder/public_token`
        run: cd legacy-shielder/public_token/ && cargo fmt --all --check

      - name: Run clippy for `shielder/public_token`
        run: cd legacy-shielder/public_token/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/public_token`
        run: cd legacy-shielder/public_token/ && cargo test

  legacy-shielder-build-contracts:
    runs-on: [self-hosted, Linux, X64, large]
    env:
      DOCKER_IMAGE: "public.ecr.aws/p6e8q1z1/ink-dev:1.0.0"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2022-11-28

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown


      - name: Build public token contract
        run: |
          docker run                         \
            -v ${{ github.workspace }}:/code \
            --platform linux/amd64           \
            ${{ env.DOCKER_IMAGE }}         \
            cargo contract build --manifest-path legacy-shielder/public_token/Cargo.toml

      - name: Build shielder contract
        run: |
          docker run                         \
            -v ${{ github.workspace }}:/code \
            --platform linux/amd64           \
            ${{ env.DOCKER_IMAGE }}         \
            cargo contract build --manifest-path legacy-shielder/contract/Cargo.toml

  shielder-rust-checks:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.76.0

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo-contract
        run: cargo install cargo-contract --version 4.0.0-rc.2

      - name: Run checks for `shielder/contract`
        run: cd shielder/ && make check-shielder

      - name: Run tests  for `shielder/contract`
        run: cd shielder/ && make tests
