name: Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  shielder-checks:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-02-14
          targets: wasm32-unknown-unknown

      - name: Install cargo-contract
        run: cargo install cargo-contract

      - name: Run checks and tests
        run: cd shielder/ && make all
