name: Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  shielder-checks:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.76.0

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo-contract
        run: cargo install cargo-contract

      - name: Run checks for `shielder/contract`
        run: cd shielder/ && make check

      - name: Run tests  for `shielder/contract`
        run: cd shielder/ && make tests
