name: Checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup component add clippy rustfmt

      - name: Install `cargo contract`
        run: cargo install dylint-link && cargo install cargo-contract


      - name: Run format check for `shielder/cli`
        run: cd shielder/cli/ && cargo fmt --all --check

      - name: Run clippy for `shielder/cli`
        run: cd shielder/cli/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/cli`
        run: cd shielder/cli/ && cargo test


      - name: Run format check for `shielder/contract`
        run: cd shielder/contract/ && cargo fmt --all --check

      - name: Run clippy for `shielder/contract`
        run: cd shielder/contract/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/contract`
        run: cd shielder/contract/ && cargo test


      - name: Run format check for `shielder/public_token`
        run: cd shielder/public_token/ && cargo fmt --all --check

      - name: Run clippy for `shielder/public_token`
        run: cd shielder/public_token/ && cargo clippy --all-features -- --no-deps -D warnings

      - name: Run tests  for `shielder/public_token`
        run: cd shielder/public_token/ && cargo test

  build-contracts:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY: public.ecr.aws/p6e8q1z1/
      DOCKER_IMAGE: ink-dev:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build public token contract
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          image: ${{ vars.DOCKER_IMAGE }}
          options: -v ${{ github.workspace }}:/code
          run: cargo contract build --manifest-path shielder/public_token/Cargo.toml

      - name: Build shielder contract
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          image: ${{ vars.DOCKER_IMAGE }}
          options: -v ${{ github.workspace }}:/code
          run: cargo contract build --manifest-path shielder/contract/Cargo.toml
