name: E2E Shielder tests.

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-checks:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run e2e tests for shielder
        run: |
          id -u
          id -g
          ls -al ~/.cargo
          cd shielder && make test-shielder-clean
